      

# Tested: 2024/08/05
# by Kasper Arfman
name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev automake
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
          pip install --user --upgrade Cython virtualenv
          pip install --user --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc
      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
      - name: Handle Java path
        run: |
          yes | buildozer -v android debug
       #export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          #sudo update-java-alternatives --set ${JAVA_HOME}
          #export PATH=$JAVA_HOME/bin:$PATH 
          
          

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.5.0
        with:
          name: package
          path: bin/*.apk
